site_name: Operating System
site_author: "Vu Anh"
google_analytics: ['UA-68978617-1', 'magizbox.com']
repo_url: https://github.com/magizbox/operating_system/
edit_uri: edit/master/docs/

pages:
- "<span class='fa fa-home'></span> Home": "index.md"
- "Linux":
  - "Linux": 'os_linux.md'
  - "Ubuntu": 'os_ubuntu.md'
  - "CentOS": 'os_centos.md'
- "Windows": 'os_windows.md'

markdown_extensions:
    - footnotes

extra_css:
  - css/book.css
  - css/course.css
  - css/video.css
  - css/custom.css
extra_javascript:
  - js/underscore.js
  - js/jquery.js
  - js/gspreadsheet.js
  - js/book.js
  - js/course.js
  - js/video.js
  - js/script.js
